### ISSUE TITLE
multiplication by sigma?

### ISSUE THREAD

**Issue by ggbioing** [JeremyLinux/PyTorch-Radial-Basis-Function-Layer#1]
https://github.com/JeremyLinux/PyTorch-Radial-Basis-Function-Layer/blob/74237e310fb07e9b8d7aaff94527909953f4e110/Torch%20RBF/torch_rbf.py#L49

This is should be ||x - c|| / sigma, right?

**Comment by JeremyLinux** [comment]
Traditionally, yes I think it would be norm divided by sigma. I chose to do norm multiplied by sigma instead to avoid the possibility of dividing by zero. It actually doesn't really matter. Just think of the self.sigma parameter as 1 / sigma if you like.

**Comment by ggbioing** [comment]
Ok, I understand your point.
There is another solution: adding a small eps to sigma.
Still, nothing prevents 1 / sigma to be < 0.

I implemented a "self.logvar" parameter (log variance) so that now:

sigma = exp(self.logvar) ^ 0.5
distance = ||x - c|| / sigma

Probably it's slower, but I feel safer because now sigma it's always strictly greater than zero.

**Comment by JeremyLinux** [comment]
Sigma has been replaced with log_sigma.
